# Site settings
title: personal Blog
SEOTitle: DDDDDDDDDF的博客
header-img: img/iot-background-with-hand-drawn-elements.jpg
email: CCCC@gmail.com
description: "当你凝视深渊，深渊也在凝视你！"
keyword: "iot, security, AI, python, crowdsening, edge intelligence,boy"
url: "http://bbqldf.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
#github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository
github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git"
# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Not good,not cool!"
# sidebar-avatar: /img/pic-myself.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`
sidebar-avatar: /img/pic-myself.pdf      # use absolute URL, seeing it's used in both `/` and `/about/`


# SNS settings
RSS: false
# weibo_username:     xxxx
zhihu_username:     xxxx
github_username:    xxxx
facebook_username:  xxxx
jianshu_username:   xxxxx
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: qiubaiying.github.io    #仓库名称
  owner: qiubaiying    #github用户名
  admin: qiubaiying
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto
#ga_domain: auto




# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#FFFFFF"
service-worker: true



# Friends
friends: [
    {
        title: "CSDN",
        href: "https://blog.csdn.net/qq_40509686?spm=1000.2115.3001.5343"
    },{
        title: "github",
        href: "https://github.com/BBQldf"
    },{
        title: "Hassbian",
        href: "https://bbs.hassbian.com/home.php?mod=space&uid=34818"
    },{
        title: "Lab",
        href: "http://nisplab.whu.edu.cn/"
    }
]
